#
# Copyright contributors to the Galasa project 
#
openapi: 3.0.3
info:
  title: Galasa Scheduler API
  version: 0.21.0

servers:
  - url: 'http://{server}:{port}'
    variables:
      server:
        default: localhost
      port:
        default: "9080"
  - url: '/'

paths:
##################################################################################
# Scheduler Status Report
##################################################################################
  /status:
    get:
      operationId: getStatus
      summary: Get Scheduler status
      tags: 
      - Status
      responses:
        '200':
          description: Report on the status of the scheduler
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
##################################################################################
# App maintenance
##################################################################################
  /app:
    get:
      operationId: getApps
      summary: Get all Apps
      tags: 
      - App
      responses:
        '200':
          description: Apps retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Apps'
  /app/{app}:
    get:
      operationId: getApp
      summary: Get App
      tags: 
      - App
      parameters:
        - name: app
          in: path
          description: Application name
          required: true
          schema:
            type: string
      responses:
        '200':
          description: App retrived
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/App'
    post:
      operationId: newApp
      summary: Create App
      tags: 
      - App
      parameters:
        - name: app
          in: path
          description: Application name
          required: true
          schema:
            type: string
      responses:
        '200':
          description: App created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/App'
    delete:
      operationId: deleteApp
      summary: Delete App
      tags: 
      - App
      parameters:
        - name: app
          in: path
          description: Application name
          required: true
          schema:
            type: string
      responses:
        '200':
          description: App deleted
##################################################################################
# Components
##################################################################################
components:
  schemas:
    Status:
      properties:
        schedulerReport:
          type: string
        apiReport:
          type: string
    App:
      properties:
        name:
          type: string
    Apps:
      properties:
        apps:
          type: array
          items: 
            $ref: '#/components/schemas/App'