#
# Copyright contributors to the Galasa project 
#
openapi: 3.0.3
info:
  title: Galasa Scheduler API
  version: 0.21.0

servers:
  - url: 'http://{server}:{port}'
    variables:
      server:
        default: localhost
      port:
        default: "9080"
  - url: '/'

paths:
##################################################################################
# Scheduler Status Report
##################################################################################
  /status:
    get:
      operationId: getStatus
      summary: Get Scheduler status
      tags: 
      - Status
      responses:
        '200':
          description: Report on the status of the scheduler
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
##################################################################################
# App maintenance
##################################################################################
  /app:
    get:
      operationId: getApps
      summary: Get all Apps
      tags: 
      - App
      responses:
        '200':
          description: Apps retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Apps'
  /app/{app}:
    get:
      operationId: getApp
      summary: Get App
      tags: 
      - App
      parameters:
      - name: app
        in: path
        description: Application name
        required: true
        schema:
          type: string
      responses:
        '200':
          description: App retrived
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/App'
    post:
      operationId: newApp
      summary: Create App
      tags: 
      - App
      parameters:
      - name: app
        in: path
        description: Application name
        required: true
        schema:
          type: string
      responses:
        '200':
          description: App created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/App'
    delete:
      operationId: deleteApp
      summary: Delete App
      tags: 
      - App
      parameters:
      - name: app
        in: path
        description: Application name
        required: true
        schema:
          type: string
      responses:
        '200':
          description: App deleted
##################################################################################
# Level maintenance
##################################################################################
  /app/{app}/level:
    get:
      operationId: getLevels
      summary: Get all Levels for an App
      tags: 
      - Level
      parameters:
      - name: app
        in: path
        description: Application name
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Levels retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Levels'
  /app/{app}/level/{level}:
    get:
      operationId: getLevel
      summary: Get Level
      tags: 
      - Level
      parameters:
      - name: app
        in: path
        description: Application name
        required: true
        schema:
          type: string
      - name: level
        in: path
        description: Level name
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Level retrived
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Level'
    post:
      operationId: newLevel
      summary: Create Level
      tags: 
      - Level
      parameters:
      - name: app
        in: path
        description: Application name
        required: true
        schema:
          type: string
      - name: level
        in: path
        description: Level name
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Level created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Level'
    delete:
      operationId: deleteLevel
      summary: Delete Level
      tags: 
      - Level
      parameters:
      - name: app
        in: path
        description: Application name
        required: true
        schema:
          type: string
      - name: level
        in: path
        description: Level name
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Level deleted
##################################################################################
# Components
##################################################################################
components:
  schemas:
    Status:
      properties:
        schedulerReport:
          type: string
        apiReport:
          type: string
#
# App
#
    App:
      properties:
        name:
          type: string
        configuration:
          type: string
    Apps:
      properties:
        apps:
          type: array
          items: 
            $ref: '#/components/schemas/App'
#
# Level
#
    Level:
      properties:
        name:
          type: string
        app:
          type: string
        configuration:
          type: string
    Levels:
      properties:
        apps:
          type: array
          items: 
            $ref: '#/components/schemas/Level'
