#
# Copyright contributors to the Galasa project 
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler
  labels:
    app: scheduler
#
#
#
spec:
#
#
#
  replicas: 1
  revisionHistoryLimit: 0
#
#
#
  selector:
    matchLabels:
      app: scheduler
  template:
    metadata:
      name: scheduler
      labels:
        app: scheduler
#
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
#
      containers:
      - name: scheduler
        image: {{ .Values.registry }}/galasadev/galasa-scheduler-amd64:{{ .Values.branch }}
        imagePullPolicy: Always
#
        env:
        - name: POSTGRESQL_URL
          value: "jdbc:postgresql://scheduler-db:5432/postgres"
