apiVersion: v1
kind: Service
metadata:
  name: scheduler-api
#
#
#
spec:
  type: ClusterIP
#
  selector:
    app: scheduler-api
#
  ports:
  - name: scheduler-api
    port: 9080
    protocol: TCP
    targetPort: 9080
