#
# Copyright contributors to the Galasa project 
#
apiVersion: v1
kind: Service
metadata:
  name: binary-scheduler-cli
#
#
#
spec:
  type: ClusterIP
#
  selector:
    app: binary-scheduler-cli
#
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
