#
# Copyright contributors to the Galasa project 
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: maven-scheduler-repo
#
#
#
spec:
  replicas: 1
  revisionHistoryLimit: 0
#
  selector:
    matchLabels:
      app: maven-scheduler-repo
  strategy:
    type: RollingUpdate

#
  template:
    metadata:
      labels:
        app: maven-scheduler-repo
#
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
#
      containers:
      - name: http
        image: {{ .Values.registry }}/galasadev/galasa-scheduler-repo:{{ .Values.branch }}
        imagePullPolicy: Always
#
        env:
        - name: CONTEXTROOT
          value: {{ .Values.branch}}/maven/scheduler
#
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: 50Mi
